# Generated by Django 3.0.3 on 2020-02-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=1000)),
                ('last_update', models.DateTimeField(verbose_name='Last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_text', models.CharField(max_length=30000)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.Testcase')),
            ],
        ),
    ]
