# Generated by Django 3.0.3 on 2020-02-11 16:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
