# Generated by Django 3.0.3 on 2020-02-11 16:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_auto_20200211_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='testcase_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='none'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_text',
            field=models.CharField(max_length=30000),
        ),
    ]
