# Generated by Django 3.0.3 on 2020-02-11 16:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_auto_20200211_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='testcase_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' '),
        ),
    ]
